services:
  integraciones-api:
    image: integraciones-api:development
    container_name: integraciones-api-development
    user: "1001:1001"
    ports:
      - "8003:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - coco-salvaje-network
    volumes:
      - ./logs:/logs
      - ./credentials:/credentials

networks:
  coco-salvaje-network:
    driver: bridge
