services:
  integraciones-api:
    image: integraciones-api
    container_name: integraciones-api
    user: "1001:1001"
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - coco-network
    volumes:
      - ./logs:/home/coco/logs
      - ./credentials:/home/coco/credentials

networks:
  coco-network:
    external: true
